ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"
  config.vm.box_version = "11.20230501.1"
  config.nfs.functional = false
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provision :docker

  # Jepsen can use this key to connect to our nodes
  config.vm.provision "shell" do |s|
    ssh_pub_key = File.readlines("vagrant_key.pub").first.strip
    gh_token = File.readlines("gh_token.json").first.strip
    s.inline = <<-SHELL
      echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
      echo -n #{gh_token} | docker login  ghcr.io -u USERNAME --password-stdin
    SHELL
  end

  nodes = 5

  (1..nodes).each do |n|
    nid = "n#{n}"
    config.vm.define nid do |node|
      node.vm.hostname = nid
      node.vm.network "private_network", ip: "192.168.56.#{100 + n}"
    end
  end
end

