roles = ["admin", "metadata-server", "worker", "log-server"]
tracing-filter = "info"
log-filter = "restate=info,slog=info,info"
log-format = "compact"
log-disable-ansi-codes = true
rocksdb-total-memory-size = "1 GB"
default-replication = 2

[admin]
heartbeat-interval = "1s"
metadata-sync-interval = "1s"
log-trim-check-interval = "5s"
log-tail-update-interval = "3s"

[metadata-server]
type = "replicated"
raft-election-tick = 10
raft-heartbeat-tick = 2
raft-tick-interval = "100ms"
status-update-interval = "1s"

[metadata-client]
type = "replicated"
addresses = ["http://127.0.0.1:5122/"] # set via environment
connect-timeout = "1s"
keep-alive-interval = "1s"
keep-alive-timeout = "1s"

[bifrost]
default-provider = "replicated"
seal-retry-interval = "1s"
auto-recovery-interval = "10s"
append-retry-min-interval = "10ms"
append-retry-max-interval = "1s"
record-cache-memory-size = "20.0 MB"

[networking]
connect-timeout = "1s"
handshake-timeout = "1s"
http2-keep-alive-interval = "1s"
http2-keep-alive-timeout = "1s"

[worker.invoker]
concurrent-invocations-limit = 1000
