roles = ["admin", "worker", "log-server"]
tracing-filter = "info"
log-filter = "restate=info,slog=info,info"
log-format = "compact"
log-disable-ansi-codes = true
rocksdb-total-memory-size = "1 GB"
default-replication = 2

[admin]
heartbeat-interval = "1s"
metadata-sync-interval = "1s"
log-trim-check-interval = "5s"
log-tail-update-interval = "3s"

[metadata-client]
type = "object-store"
path = "s3://<metadata-bucket>" # set via environment

[bifrost]
default-provider = "replicated"
seal-retry-interval = "1s"
auto-recovery-interval = "10s"
append-retry-min-interval = "10ms"
append-retry-max-interval = "1s"
record-cache-memory-size = "20.0 MB"

[networking]
connect-timeout = "1s"
handshake-timeout = "1s"
http2-keep-alive-interval = "1s"
http2-keep-alive-timeout = "1s"

[worker.invoker]
concurrent-invocations-limit = 1000
