name: Restate Jepsen tests
description: "Run Restate Jepsen tests"
inputs:
  clusterName:
    description: 'Jepsen workers cluster AWS stack name'
    required: true
  bucketName:
    description: "Storage bucket for cluster - will be created on-demand if unset"
    required: false

runs:
  using: "composite"

  steps:
    - name: Destroy cluster
      shell: bash
      working-directory: ./jepsen
      run: just destroy-aws-cluster "${{ inputs.clusterName }}" "${{ inputs.bucketName }}"
