name: Run Restate Jepsen tests
description: "Runs Restate Jepsen test suite. Assumes you have already called the `setup` action."
inputs:
  restateImageId:
    description: 'Restate image (ignored if PR set)'
    required: false
    default: 'ghcr.io/restatedev/restate:main'
  restatePr:
    description: 'Use CI Docker image from PR (ignored if commit is set)'
    required: false
  restateCommit:
    description: 'Use CI Docker image from Restate commit'
    required: false
  clusterName:
    description: 'Jepsen workers cluster AWS stack name'
    required: true
  testConfig:
    description: 'Jepsen test run configuration'
    required: false
    default:  '{ "workloads": "set-vo", "nemeses": "partition-random-node", "duration": "60", "rate": "10", "concurrency": "5n", "testCount": "1" }'

runs:
  using: "composite"

  steps:
    - name: Download Restate Docker image
      if: inputs.restateCommit != '' || inputs.restatePr != ''
      uses: dawidd6/action-download-artifact@v3
      with:
        repo: restatedev/restate
        workflow: ci.yml
        pr: ${{ inputs.restatePr }}
        commit: ${{ inputs.restateCommit }}
        name: restate.tar
        workflow_conclusion: ""
        path: ./jepsen

    - name: Run Jepsen tests
      id: jepsen-tests
      shell: bash
      working-directory: ./jepsen
      run: |
        set +e

        if [ -f restate.tar ]; then
          JEPSEN_RESTATE_IMAGE='localhost/restatedev/restate-commit-download:latest --image-tarball restate.tar'
        else
          JEPSEN_RESTATE_IMAGE='${{ inputs.restateImageId || 'ghcr.io/restatedev/restate:main' }}'
        fi

        STATUS=0

        for WORKLOAD in ${{ fromJSON(inputs.testConfig).workloads || 'set-vo' }}; do
          for NEMESIS in ${{ fromJSON(inputs.testConfig).nemeses || 'partition-random-node' }}; do
            echo "::group::Jepsen workload: ${WORKLOAD} nemesis: ${NEMESIS}"

            lein run test \
              --nodes-file aws/nodes.txt \
              --username admin \
              --ssh-private-key aws/private-key.pem \
              --workload ${WORKLOAD} --nemesis ${NEMESIS} \
              --image ${JEPSEN_RESTATE_IMAGE} \
              --time-limit ${{ fromJSON(inputs.testConfig).duration || 30 }} \
              --rate ${{ fromJSON(inputs.testConfig).rate || 10 }} \
              --concurrency ${{ fromJSON(inputs.testConfig).concurrency || '5n' }} \
              --test-count ${{ fromJSON(inputs.testConfig).testCount || '1' }} \
              --leave-db-running ${{ inputs.retainCluster || 'false' }}

            if [ $? -ne 0 ]; then
              STATUS=1
              echo "::error::Test workload: ${WORKLOAD} nemesis: ${NEMESIS} failed"
            fi

            echo "::endgroup::"
          done
        done

        exit ${STATUS}

    - name: Upload Jepsen output
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: jepsen-store
        path: ./jepsen/store
